openfoodfacts/nutripatrol-frontend

.env.local, .env.preprod, .env.prod, .github/workflows/deploy.yml, .gitignore, index.html
=> fix: set all environment files local, preprod, prod

.github/workflows/deploy.yml
Preparing frontend for preprod and prod
=> fix: fix missing dash

src/components/ImageTicket.tsx, src/components/Ticket.tsx, src/components/TicketsButtons.tsx, src/main.tsx, src/pages/ImageModerationPage.tsx, src/pages/ModerationPage.tsx
=> fix: display reasons from flags

src/components/AppBar.tsx
=> fix: enlarge navlink

src/App.tsx, src/components/AppBar.tsx, src/components/Layouts/LayoutMenu.tsx
Avatar color in navbar
Avatar have to be green when you are logged in, and red/orange when you are not
=> fix: key fix

src/pages/HomePage.tsx, src/pages/ImageModerationPage.tsx, src/pages/ModerationPage.tsx
fix: loading bug : No ticket appear before loading data
fix it : add a loading feature
=> Loading pages

src/pages/HomePage.tsx, src/pages/ImageModerationPage.tsx, src/pages/LoginPage.tsx, src/pages/ModerationPage.tsx, src/pages/NonModeratorPage.tsx, src/pages/NotFound.tsx
Better use of Mui by using Typography Component
=> fix: Use MUI components instead of html

src/components/AppBar.tsx, src/pages/ImageModerationPage.tsx, src/pages/ModerationPage.tsx
=> Fix react issues

src/components/AppBar.tsx, src/off.ts
=> fix: logout delete sessions cookie

src/components/AppBar.tsx
Make the off logo responsive on the navbar
=> fix: responsive logo

src/App.tsx
=> refactor routes

src/components/AppBar.tsx, src/components/TicketsButtons.tsx, src/pages/HomePage.tsx
=> fix: add get started button

src/components/ImageTicket.tsx, src/components/Ticket.tsx, src/components/TicketsButtons.tsx, src/pages/ImageModerationPage.tsx, src/pages/LoginPage.tsx, src/pages/ModerationPage.tsx, src/pages/NonModeratorPage.tsx, src/pages/NotFound.tsx
=> Responsive tickets

README.md
- add https://nutripatrol.openfoodfacts.net/ to README
=> add https://nutripatrol.openfoodfacts.net/ to README

src/components/ImageTicket.tsx
Get minified images for tickets thumbnails
=> fix: get minified images

src/components/ImageTicket.tsx, src/components/Ticket.tsx, src/components/TicketsButtons.tsx, src/pages/ImageModerationPage.tsx, src/pages/ModerationPage.tsx
remove hard reload of tickets when you update status of ticket or image ticket
use the useState hook instead
=> fix: useState remove button

src/components/ImageTicket.tsx, src/components/Paginate.tsx, src/pages/ImageModerationPage.tsx, src/pages/ModerationPage.tsx
=> Paginate tickets

src/pages/ImageModerationPage.tsx, src/pages/ModerationPage.tsx
=> fix: Filter reasons

src/App.tsx, src/pages/ImageModerationPage.tsx
Updates filter en datas when changes
(Add new moderator)
=> fix: Updates filter en datas when changes

src/App.tsx
=> fix: add moderators

src/App.tsx, src/pages/HomePage.tsx, src/pages/Tutorial.tsx
Add a text tutorial to explain how to manage image tickets
=> fix: tutorial page

src/components/InfoModal.tsx, src/pages/ImageModerationPage.tsx
Filter in Image moderation can accept several keywords.
It' a little confusing. 
This PR have to make the filter give only one reason
=> Unique keyword filter

src/App.tsx, src/pages/ImageModerationPage.tsx
Fix : #7 
And fix some UI issue
=> UI UX improve

src/App.tsx, src/components/AppBar.tsx, src/components/AuthAlert.tsx, src/components/ImageTicket.tsx, src/components/Layouts/LayoutMenu.tsx, src/const/moderators.ts
Reload automatically when you are logged In
=> Autoreload login

src/App.tsx, src/components/Layouts/LayoutMenu.tsx, src/pages/FlagFormPage.tsx
use context instead of props to provide isLoggedIn and userName in children components.
Issue #53
=> Refactor app

src/components/AppBar.tsx, src/components/Layouts/LayoutMenu.tsx
use context to provide isLoggedIn in the Appbar instead of useState
=> fix: use context to provide isLoggedIn

src/components/ImageTicket.tsx, src/components/InfoModal.tsx, src/components/Ticket.tsx, src/pages/ImageModerationPage.tsx, src/pages/ModerationPage.tsx
Add comments and reasons on image tickets and product tickets
=> Display reasons comments

src/const/flagsConst.ts
Fix reasons consts for flags form
=> fix: reasons

src/components/InfoModal.tsx, src/pages/FlagFormPage.tsx
=> fix: selected images and image id

README.md, src/components/InfoModal.tsx
=> fix: resize modal infos

src/App.tsx, src/pages/FlagFormPage.tsx, src/pages/ThanksPage.tsx
Create a Thanks page to redirect users after flagging a product or image
#65
=> feat: thanks page after flag form

src/components/ImageTicket.tsx, src/components/InfoModal.tsx
make preview modal scrollable for long list of images
=> fix: make modal scrollable

src/App.tsx, src/components/ImageTicket.tsx, src/components/InfoModal.tsx
Preview upgrades 
- Change order of infos 
- Add Categories and ingrédients
LogIn 
- Remove green pop up
=> fix: Preview upgrades

.github/workflows/git
- Auto-add mockup required to OFF design backlog
=> ci: off-design

src/components/InfoModal.tsx
Hide some infos 
Dispay all selected images by languages
#83 & #81
=> feat: Modal hide infos - Display all selected images

src/App.tsx, src/components/InfoModal.tsx
- Use the product opener API to check if authenticated user is moderator.
- Remove the Whitelist of moderators
=> feat: Use /cgi/auth.pl from PO to check if user is moderator

src/contexts/login.tsx
Testing new way to check if user is Moderator
=> fix: add isModerator to login context

.env.local, .env.preprod, .env.prod, src/components/DeleteButton.tsx, src/components/InfoModal.tsx
Add a button to delete image directly in nutripatrol if needed
This button have to be visible on each ticket to make moderation easeier
=> feat: Delete images from image tickets in nutripatrol

src/components/InfoModal.tsx
=> fix: fix invalid image URL generation

src/pages/HomePage.tsx
Change the content of the Nutripatrol HomePage
=> feat: new content for the home page

src/components/Ticket.tsx, src/pages/ModerationPage.tsx
Display user_id in product tickets
#154
=> feat: display user_id on moderation tickets

src/index.css
Link are not currently visible on the home page. Make them visible in typography texts.
**Note:** I'm not sure it's the right way to do it, feel free to do it the right way !
=> feat: make links visible on home-page and texts
